services:
  - type: web
    name: django-finance-tracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      DJANGO_SUPERUSER_USERNAME=admin \
      DJANGO_SUPERUSER_PASSWORD=adminpass \
      DJANGO_SUPERUSER_EMAIL=admin@example.com \
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com