services:
  - type: web
    name: django-finance-tracker
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput && \
      DJANGO_SUPERUSER_USERNAME=myadmin \
      DJANGO_SUPERUSER_EMAIL=myadmin@example.com \
      DJANGO_SUPERUSER_PASSWORD='MyStrongPass987' \
      python manage.py createsuperuser --noinput || true && \
      gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        value: postgresql://fintrack_db_240z_user:AnIp4QAOotf3E2K7RYR9nyv7dUS83bJD@dpg-d2bd3evdiees73eknak0-a.oregon-postgres.render.com/fintrack_db_240z   # replace with actual Render DB URL